### ISSUE TITLE
ImportError: cannot import name is_json_value_header

### ISSUE THREAD

**Issue by skynet** [aws/aws-cli#2600]
```
ImportError: cannot import name is_json_value_header
```

Started to get this after upgrading to 1.11.83

**Comment by skynet** [comment]
`pip install -U botocore`

fixed-it

**Comment by dskrvk** [comment]
Related to https://github.com/aws/aws-cli/issues/2526
