### ISSUE TITLE
aws s3 cp throws unexpected keyword argument 'max_bandwidth' on awscli 1.14.0

### ISSUE THREAD

**Issue by squidarth** [aws/aws-cli#3006]
Hi--after upgrading our version of `awscli` to 1.14.0, we noticed we were unable to run `aws s3 cp`. Seeing the following error:

```
$ aws s3 cp local_file.txt s3://bucket/remote_file
__init__() got an unexpected keyword argument 'max_bandwidth'

$ aws --version
aws-cli/1.14.0 Python/2.7.12 Linux/4.4.0-64-generic botocore/1.8.4
```

We are running version 1.14.0 of the `awscli`, with `botocore` version 1.8.4, on python 2.7.12.

We've reverted back to version 1.13.0 for now.

Thanks for looking into this, and let me know if you need any more information to replicate this bug.

**Comment by joguSD** [comment]
This is because we failed to bump the minimum required version of s3transfer. This is rectified in https://github.com/aws/aws-cli/pull/3003

In the mean time you can manually upgrade s3transfer like so: `pip install --upgrade s3transfer`

**Comment by squidarth** [comment]
Great, thank you!
