### ISSUE TITLE
s3 sync broken in 1.14.0 - unexpected keyword argument 'max_bandwidth'

### ISSUE THREAD

**Issue by abrom** [aws/aws-cli#3007]
```
> aws s3 sync . s3://<bucket>/<path> --delete

__init__() got an unexpected keyword argument 'max_bandwidth'
```

Was working fine with 1.13.0 yesterday.

Installation via bundled installer method (`awscli-bundle.zip`)

Note, we do not configure any defaults via file or CLI. Only args passed through are secret access key, access key id and default region via ENV.

Likely related to #2997

HTH

**Comment by hafizramly** [comment]
I had the same issue with s3 sync

My version : 
**aws-cli/1.14.0 Python/2.6.5 Linux/2.6.32-377-ec2 botocore/1.8.4**

Step to produce :
```
aws s3 sync s3://bucket/folder/ /local/folder/ --region us-east-1 --only-show-errors

__init__() got an unexpected keyword argument 'max_bandwidth'
```

**Comment by joguSD** [comment]
This has been fixed in `v1.14.1`. Updating again should fix it.


Duplicate: https://github.com/aws/aws-cli/issues/3006

**Comment by kelleydon** [comment]
I upgraded to v1.14.2 and I'm still getting the error with aws cp. 

Steps to produce: 

`aws s3 cp --region us-east-1 s3://file_location file_location`

**Comment by joguSD** [comment]
@kelleydon 
I think the upgrade behavior is going to depend on the version of pip, if you're still running into the issue manually update s3transfer by doing:
```
pip install --upgrade s3transfer
```

**Comment by hafizramly** [comment]
Its now working correctly after upgrading to the newer version

aws-cli/1.14.2 Python/2.7.6 Linux/3.13.0-135-generic botocore/1.8.6

**Comment by rflaperuta** [comment]
Just got to this problem, here follows the log with --debug option:

2017-12-05 10:21:14,376 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.14.3 Python/3.6.3 Linux/4.10.0-40-generic botocore/1.8.7

2017-12-05 10:21:14,376 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['s3', 'sync', 's3://ns-coletor-geral-prd/', '.', '--region', 'us-west-2', '--include=/log-inf
ra/coletorws/20171205/*.log', '--debug']
2017-12-05 10:21:14,376 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7f9f14103378>
2017-12-05 10:21:14,377 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-12-05 10:21:14,377 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f9f14b701e0>
2017-12-05 10:21:14,377 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-12-05 10:21:14,377 - MainThread - botocore.session - DEBUG - Loading variable credentials_file from defaults.
2017-12-05 10:21:14,377 - MainThread - botocore.session - DEBUG - Loading variable config_file from defaults.
2017-12-05 10:21:14,377 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-12-05 10:21:14,377 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_timeout from defaults.
2017-12-05 10:21:14,377 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-12-05 10:21:14,377 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_num_attempts from defaults.
2017-12-05 10:21:14,377 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-12-05 10:21:14,377 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7f9f17427d90>
2017-12-05 10:21:14,377 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-12-05 10:21:14,377 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3: calling handler <function add_waiters at 0x7f9f14109620>
2017-12-05 10:21:14,378 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.s3.anonymous: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,378 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sync: calling handler <function register_sync_strategies at 0x7f9f140ffa60>
2017-12-05 10:21:14,378 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sync: calling handler <function add_waiters at 0x7f9f14109620>
2017-12-05 10:21:14,378 - MainThread - botocore.hooks - DEBUG - Event building-arg-table.sync: calling handler <bound method BaseSync.add_sync_argument of <awscli.customizations.s3.syncs
trategy.sizeonly.SizeOnlySync object at 0x7f9f14041b00>>
2017-12-05 10:21:14,379 - MainThread - botocore.hooks - DEBUG - Event building-arg-table.sync: calling handler <bound method BaseSync.add_sync_argument of <awscli.customizations.s3.syncs
trategy.exacttimestamps.ExactTimestampsSync object at 0x7f9f14041be0>>
2017-12-05 10:21:14,379 - MainThread - botocore.hooks - DEBUG - Event building-arg-table.sync: calling handler <bound method BaseSync.add_sync_argument of <awscli.customizations.s3.syncs
trategy.delete.DeleteSync object at 0x7f9f14041cc0>>
2017-12-05 10:21:14,380 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.paths: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,380 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.dryrun: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,380 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.sync: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f9f14bc25f8>
2017-12-05 10:21:14,380 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.quiet: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,380 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.sync: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f9f14bc25f8>
2017-12-05 10:21:14,380 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.anonymous: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,381 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.acl: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,381 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.follow-symlinks: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,381 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.sync: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f9f14bc25f8>
2017-12-05 10:21:14,381 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.anonymous: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,381 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.sse: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,381 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.sse-c: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,381 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.sse-c-key: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,381 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.sse-kms-key-id: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,381 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.sse-c-copy-source: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,381 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.sse-c-copy-source-key: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,381 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.storage-class: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,381 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.grants: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,381 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.website-redirect: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,381 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.content-type: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,381 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.cache-control: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,381 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.content-disposition: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,381 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.content-encoding: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,381 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.content-language: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,381 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.expires: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,382 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.source-region: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,382 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.only-show-errors: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,382 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.sync: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f9f14bc25f8>
2017-12-05 10:21:14,382 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.anonymous: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,382 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.page-size: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,382 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.ignore-glacier-warnings: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,382 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.sync: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f9f14bc25f8>
2017-12-05 10:21:14,382 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.force-glacier-transfer: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,382 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.sync: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f9f14bc25f8>
2017-12-05 10:21:14,382 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.metadata: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,382 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.metadata-directive: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,382 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.size-only: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,382 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.sync: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f9f14bc25f8>
2017-12-05 10:21:14,382 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.exact-timestamps: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,382 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.sync: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f9f14bc25f8>
2017-12-05 10:21:14,382 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.sync.delete: calling handler <function uri_param at 0x7f9f14c017b8>
2017-12-05 10:21:14,382 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.sync: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f9f14bc25f8>
2017-12-05 10:21:14,382 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-12-05 10:21:14,382 - MainThread - botocore.session - DEBUG - Loading variable ca_bundle from defaults.
2017-12-05 10:21:14,382 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-12-05 10:21:14,383 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2017-12-05 10:21:14,383 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2017-12-05 10:21:14,383 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2017-12-05 10:21:14,383 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2017-12-05 10:21:14,383 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2017-12-05 10:21:14,383 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python3.6/site-packages/botocore/data/endpoints.json
2017-12-05 10:21:14,385 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-12-05 10:21:14,386 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python3.6/site-packages/botocore/data/s3/2006-03-01/service-2.json
2017-12-05 10:21:14,392 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f9f15a59158>
2017-12-05 10:21:14,392 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f9f15a4fea0>
2017-12-05 10:21:14,393 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2017-12-05 10:21:14,396 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2017-12-05 10:21:14,396 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2017-12-05 10:21:14,397 - MainThread - botocore.client - DEBUG - Defaulting to S3 virtual host style addressing with path style addressing fallback.
2017-12-05 10:21:14,397 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-12-05 10:21:14,397 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-12-05 10:21:14,397 - MainThread - botocore.session - DEBUG - Loading variable ca_bundle from defaults.
2017-12-05 10:21:14,397 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-12-05 10:21:14,397 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2017-12-05 10:21:14,397 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-12-05 10:21:14,398 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f9f15a59158>
2017-12-05 10:21:14,398 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f9f15a4fea0>
2017-12-05 10:21:14,398 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2017-12-05 10:21:14,398 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2017-12-05 10:21:14,400 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2017-12-05 10:21:14,400 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2017-12-05 10:21:14,400 - MainThread - botocore.client - DEBUG - Defaulting to S3 virtual host style addressing with path style addressing fallback.
2017-12-05 10:21:14,400 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-12-05 10:21:14,400 - MainThread - botocore.session - DEBUG - Loading variable ca_bundle from defaults.
2017-12-05 10:21:14,401 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-12-05 10:21:14,401 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2017-12-05 10:21:14,401 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-12-05 10:21:14,401 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f9f15a59158>
2017-12-05 10:21:14,401 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f9f15a4fea0>
2017-12-05 10:21:14,401 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2017-12-05 10:21:14,415 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2017-12-05 10:21:14,416 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2017-12-05 10:21:14,416 - MainThread - botocore.client - DEBUG - Defaulting to S3 virtual host style addressing with path style addressing fallback.
2017-12-05 10:21:14,416 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/awscli/clidriver.py", line 207, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python3.6/site-packages/awscli/customizations/commands.py", line 190, in __call__
    parsed_globals)
  File "/usr/local/lib/python3.6/site-packages/awscli/customizations/commands.py", line 187, in __call__
    return self._run_main(parsed_args, parsed_globals)
  File "/usr/local/lib/python3.6/site-packages/awscli/customizations/s3/subcommands.py", line 697, in _run_main
    return cmd.run()
  File "/usr/local/lib/python3.6/site-packages/awscli/customizations/s3/subcommands.py", line 1025, in run
    self._client, result_queue)
  File "/usr/local/lib/python3.6/site-packages/awscli/customizations/s3/s3handler.py", line 84, in __call__
    self._runtime_config)
  File "/usr/local/lib/python3.6/site-packages/awscli/customizations/s3/transferconfig.py", line 119, in create_transfer_config_from_runtime_config
    return TransferConfig(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'max_bandwidth'
2017-12-05 10:21:14,417 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

__init__() got an unexpected keyword argument 'max_bandwidth'

**Comment by jamesls** [comment]
For anyone that's still running into this issue, make sure you have the latest version of s3transfer installed.  This should automatically be handled via pip (our dependency on s3transfer has been updated https://github.com/aws/aws-cli/blob/develop/setup.py#L30), but in case not, please run `pip install --upgrade s3transfer`.

Let us know if the above steps are still not working for you.

**Comment by jgramoll** [comment]
I am still getting the error.

`aws --version
aws-cli/1.14.16 Python/2.7.6 Linux/3.13.0-137-generic botocore/1.8.20`

`pip show s3transfer
"Name: s3transfer", 
"Version: 0.1.12"`

**Comment by sakers** [comment]
aws --version
aws-cli/1.14.22 Python/2.7.5 Linux/3.10.0-693.5.2.el7.x86_64 botocore/1.8.26

pip show s3transfer
Name: s3transfer
Version: 0.1.12

**Comment by meowtochondria** [comment]
just a pointer in case someone lands here - check via your package manager if your OS has previous version of `s3transfer` installed. It can happen when you used `apt` or `yum` (or your distro's package manager to install awscli). `python2-s3transfer` (v0.10.0) was still hanging around for me even when i removed `awscli` using package manager. I had to reinstall `s3transfer` using `pip` after removing `python2-s3transfer`.

**Comment by karnauskas** [comment]
Got same `__init__() got an unexpected keyword argument 'max_bandwidth'`.

```
aws --version
aws-cli/1.14.28 Python/2.7.5 Linux/3.10.0-693.5.2.el7.x86_64 botocore/1.8.35
```

**Comment by CiliaFred** [comment]
Got the same using `yum install awscli`
Fixed it by using pip to install awscli
`yum install -y curl python36`
`curl https://bootstrap.pypa.io/3.3/get-pip.py`
`python36 get-pip.py`
`pip install awscli==1.15.19`

**Comment by pbudzon** [comment]
awscli package in Centos base yum repo seems to be broken (this affects not only the AMI). 
On "GenericCloud" image removing yum package and installing awscli from pip2 solved the problem.
On AMI had to remove the yum package and install cli from pip3 (pip2 version was also broken).

**Comment by heraldb** [comment]
Indeed, installing awscli via pip worked fine. I used python3, just like CiliaFred

What I did on Centos 7.5:

```
yum remove awscli python-s3transfer
yum install -y python36 python34-pip
pip3 install awscli==1.15.19
```

**Comment by IlariExove** [comment]
Fedora EPEL maintainers should be notified to get this fixed in CentOS distros. I'll create a new EPEL Bugzilla ticket about this if I can't find an existing one there.

**Comment by PascalBourdier** [comment]
https://access.redhat.com/errata/RHBA-2018:3123
