### ISSUE TITLE
'OperationModel' object has no attribute 'service_model'

### ISSUE THREAD

**Issue by russellneufeld** [aws/aws-cli#1229]
Latest version of aws cli fails with 'OperationModel' object has no attribute 'service_model' for several elasticache commands.  It may fail for others, I haven't checked, but here's an example:

~# /usr/local/bin/aws --version
aws-cli/1.7.15 Python/2.7.6 Linux/3.13.0-46-generic

~# /usr/local/bin/aws elasticache describe-replication-groups --region $AWS_REGION --replication-group-id sdlkjfhsd

'OperationModel' object has no attribute 'service_model'

With version 1.7.13 this works fine.

**Comment by kyleknap** [comment]
@russellneufeld 
How did you install the CLI? I have a feeling that you are using an old version of botocore. You need to be using the latest version of botocore for the latest version of the CLI to work.

**Comment by russellneufeld** [comment]
It's install via pip, via a requirements.txt file which simply has the line 'awscli'.  (That is, no version specification.)

**Comment by kyleknap** [comment]
We will look to see if we can reproduce it. Could you also let us know what botocore version you are using in that environment? You can do so by typing:
```
import botocore
print(botocore.__version__)
```

**Comment by kyleknap** [comment]
I tried reproducing the issue with no luck. My ``requirements.txt`` looks like:
```
awscli
```

and I ran:
```
pip install -r requirements.txt
```
@russellneufeld 
Is this any different than the way you did it? I did this in a brand new virtual environment. I also tried it in a virtual environment with an old version of botocore installed.

**Comment by russellneufeld** [comment]
>>> import botocore
>>> print(botocore.__version__)
0.96.0

I think you're right though.  My botocore was 0.94.0 on a different machine.  I don't specify botocore in my requirements.txt file, and somehow pip must have pulled in an older version.  When I upgraded to 0.96.0 the command started working.  I guess I should specify the latest botocore in my requirements.txt file as well.  Thanks.  Never needed to do this in the past, but it's not a big deal to add it now.

**Comment by russellneufeld** [comment]
OK, I think I see what's going on - I'm running on an Ubuntu 14.04LTS ami which must have botocore version 0.94.0 pre-installed.  That hasn't been a problem before, but now the latest version of awscli needs 0.96.0.  Simply installing awscli doesn't grab the latest botocore.

**Comment by kyleknap** [comment]
Good to hear that you got it too work. It is still strange that the latest botocore was not picked up because the latest version of botocore is a requirement in the current version of the CLI. Going to leave this issue open for a while longer just in case others experience the same problem.

**Comment by russellneufeld** [comment]
ok.  Thanks for the quick responses.

**Comment by jamesls** [comment]
Haven't heard any other reports of this, going to close out issue.
