### ISSUE TITLE
aws cli 1.10.43 has a problem with emr create-default-roles. Error: 'ClientError' object has no attribute 'error_message'

### ISSUE THREAD

**Issue by gwsu2008** [aws/aws-cli#2048]
Hi,

After upgrading to latest aws cli 1.10.43, the command to emr create-default-roles is failing with error: 'ClientError' object has no attribute 'error_message'. The command was working in version 1.10.38.

debug logging:
```
2016-06-30 09:15:56,212 - MainThread - botocore.hooks - DEBUG - Event after-call.iam.GetRole: calling handler <function json_decode_policies at 0x1eb6140>
2016-06-30 09:15:56,213 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/aws/lib/python2.7/site-packages/awscli/clidriver.py", line 186, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/aws/lib/python2.7/site-packages/awscli/clidriver.py", line 379, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/aws/lib/python2.7/site-packages/awscli/customizations/commands.py", line 187, in __call__
    return self._run_main(parsed_args, parsed_globals)
  File "/usr/local/aws/lib/python2.7/site-packages/awscli/customizations/emr/command.py", line 45, in _run_main
    return self._run_main_command(parsed_args, parsed_globals)
  File "/usr/local/aws/lib/python2.7/site-packages/awscli/customizations/emr/createdefaultroles.py", line 151, in _run_main_command
    if self._check_if_role_exists(role_name, parsed_globals):
  File "/usr/local/aws/lib/python2.7/site-packages/awscli/customizations/emr/createdefaultroles.py", line 225, in _check_if_role_exists
    if role_not_found_msg in e.error_message:
AttributeError: 'ClientError' object has no attribute 'error_message'
2016-06-30 09:15:56,217 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255
```

Thanks

Guang

**Comment by JordonPhillips** [comment]
I see what happened. The CLI used to have its own error handling which was not removed when botocore was separated. We removed the special error handling very recently. While we did change instances where ClientError was used, it seems that particular customization used `except Exception` so we didn't catch it when making the change. Thanks for reporting! I'll get on it.

**Comment by pari-agsft** [comment]
Hi, I am facing same issue with 1.10.45. 

How do I downgrade aws cli to 1.10.38, any idea?

Thanks
pari

**Comment by pari-agsft** [comment]
Just to update. I was trying to create emr roles using 
aws emr create-default-roles
It didn't work with 1.10.38 either but with 1.10.30.

Thanks
Pari

**Comment by adampryor** [comment]
I downgraded using: sudo pip install awscli==1.10.30

**Comment by JordonPhillips** [comment]
Forgot to close this out when the fix merged. This should be working now.
