### ISSUE TITLE
Using `--no-paginate` with `aws cloudformation describe-stacks` throws error

### ISSUE THREAD

**Issue by jszwedko** [aws/aws-cli#1993]
Version: `aws-cli/1.10.34 Python/2.7.9 Linux/3.16.0-4-amd64 botocore/1.4.24`

When I attempt to run `aws cloudformation describe-stacks --no-paginate --region us-west-2` I receive:

    'Namespace' object has no attribute 'page_size'

This does not happen if I do not use the `--no-paginate` flag.

**Comment by jszwedko** [comment]
https://forums.aws.amazon.com/thread.jspa?threadID=231962 appears to be a similar issue

**Comment by jamesls** [comment]
Confirmed bug, full traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 186, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 379, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 518, in __call__
    parsed_globals=parsed_globals)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 621, in _emit
    return self._session.emit(name, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/session.py", line 683, in emit
    return self._events.emit(event_name, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/awscli/customizations/paginate.py", line 189, in check_should_enable_pagination
    ensure_paging_params_not_set(parsed_args, shadowed_args)
  File "/usr/local/lib/python2.7/site-packages/awscli/customizations/paginate.py", line 196, in ensure_paging_params_not_set
    p not in shadowed_params and getattr(parsed_args, p)]
AttributeError: 'Namespace' object has no attribute 'page_size'
```

Seems to be caused by: https://github.com/aws/aws-cli/pull/1958

cc @JordonPhillips

**Comment by jszwedko** [comment]
Indeed, this issue appears to have been introduced by 12aa790f94e87b64ba2f96bf0237e03e752ae8ed.

**Comment by jamesls** [comment]
https://github.com/aws/aws-cli/pull/1994 should fix the issue.
